name: Challenge Workflow
run-name: ${{ github.actor }} is hunting for the flag 🚀
on:
  - push
jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: /challenge/repository
      - run: exit 1 # Replace this with the steps of your workflow!